import { useState } from "react"
export default function PlayerForm({ onSaved, player }) {
  const [name, setName] = useState(player?.name || ""), [shirtNumber, setShirtNumber] = useState(player?.shirt_number || ""), [image, setImage] = useState(player?.image || ""), [preview, setPreview] = useState(player?.image || ""), [loading, setLoading] = useState(false), [error, setError] = useState("")
  function handleImage(e) { const file = e.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return setError("اختر ملف صورة صالح"); 
    // if (file.size > 2 * 1024 * 1024) return setError("حجم الصورة يجب ألا يتجاوز 2MB"); 
    const reader = new FileReader(); reader.onload = () => { setImage(reader.result); setPreview(reader.result); setError("") }; reader.readAsDataURL(file) }
  async function submit(e) { e.preventDefault(); setLoading(true); setError(""); const res = await fetch(player ? `/api/players/${player.id}` : "/api/players", { method: player ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, shirtNumber, image }) }); const data = await res.json(); if (!res.ok) setError(data.error || "حدث خطأ"); else onSaved(data); setLoading(false) }
  return <form onSubmit={submit} className="space-y-4"><input required value={name} onChange={e => setName(e.target.value)} placeholder="اسم اللاعب" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-violet-500" /><input required type="number" min="0" max="99" value={shirtNumber} onChange={e => setShirtNumber(e.target.value)} placeholder="رقم القميص" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-violet-500" /><label className="block cursor-pointer rounded-xl border border-dashed border-violet-500/40 bg-violet-500/5 p-4 text-center text-sm text-gray-300">اختيار صورة اللاعب<input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleImage} className="hidden" /></label>{preview && <img src={preview} className="mx-auto h-24 w-24 rounded-2xl object-cover border border-white/10" />}{error && <div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}<button disabled={loading} className="w-full rounded-xl bg-gradient-to-r from-violet-600 to-pink-500 px-4 py-3 font-bold disabled:opacity-50">{loading ? "جاري الحفظ..." : "حفظ اللاعب"}</button></form>
}
